team: Grupo21
board: https://github.com/orgs/MISW-4301-Desarrollo-Apps-en-la-Nube/projects/76/views/1
url: 34.98.64.22
user-management:
  folder: auth
  authors:
    - a.fajardor@uniandes.edu.co
post-management:
  folder: posts
  authors:
    - c.riverao@uniandes.edu.co
offer-management:
  folder: offers
  authors:
    - rd.ortizr1@uniandes.edu.co
journey-management:
  folder: trayecto
  authors:
    - j.ochoao@uniandes.edu.co
score-management:
  folder: scores
  authors:
    - c.riverao@uniandes.edu.co
create-offers-management:
  folder: create-offers
  authors:
    - c.riverao@uniandes.edu.co
create-post-management:
  folder: create-posts
  authors:
    - j.ochoao@uniandes.edu.co

# Los siguientes componentes fueron desarrollados por todos los miembros del grupo mediante pair-programming
funcion-bucket:
  folder: funcion-bucket
funcion-email:
  folder: funcion-email
funcion-verify:
  folder: funcion-verify
funcion-webhook:
  folder: funcion-webhook