version: "3"
services:
  ABCJobs_db:
    container_name: ABCJobs_db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ABCJobs
    ports:
      - "5432:5432"
    volumes:
      - ./ABCJobs/:/db/

  auth-microservice:
    container_name: auth-microservice
    build: ./auth
    working_dir: /auth_microservice/
    env_file: ./auth/.env
    depends_on:
      - ABCJobs_db

  usuarios-microservice:
    container_name: usuarios-microservice
    build: ./usuarios
    working_dir: /usuarios_microservice/
    env_file: ./usuarios/.env
    depends_on:
      - ABCJobs_db
  
  proyectos-microservice:
    container_name: proyectos-microservice
    build: ./proyectos
    working_dir: /proyectos_microservice/
    env_file: ./proyectos/.env
    depends_on:
      - ABCJobs_db

  tech-skills-microservice:
    container_name: tech-skills-microservice
    build: ./tech-skills
    working_dir: /tech-skills_microservice/
    env_file: ./tech-skills/.env
    depends_on:
      - ABCJobs_db

  offers-microservice:
    container_name: offers-microservice
    build: ./offers
    working_dir: /offers_microservice/
    env_file: ./offers/.env
    depends_on:
      - ABCJobs_db

  nginx:
    container_name: nginx
    ports:
      - "3000:80"
    build: ./nginx
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - auth-microservice
      - usuarios-microservice
      - proyectos-microservice
      - tech-skills-microservice
      - offers-microservice