version: "3"
services:
  auth-microservice:
    container_name: auth-microservice
    build: ./auth
    working_dir: /auth_microservice/
    env_file: ./auth/.env
    depends_on:
      - ABCJobs_db

  usuarios-microservice:
    container_name: usuarios-microservice
    build: ./usuarios
    working_dir: /usuarios_microservice/
    env_file: ./usuarios/.env
    depends_on:
      - ABCJobs_db
  
  proyectos-microservice:
    container_name: proyectos-microservice
    build: ./proyectos
    working_dir: /proyectos_microservice/
    env_file: ./proyectos/.env
    depends_on:
      - ABCJobs_db

  ABCJobs_db:
    container_name: ABCJobs_db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ABCJobs
    ports:
      - "5432:5432"
    volumes:
      - ./ABCJobs/:/db/

  nginx:
    ports:
      - 3000:80
    build: ./nginx
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-microservice
      - usuarios-microservice
      - proyectos-microservice
