###################################
# INGRESS
###################################
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  labels:
    name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /auth
        backend:
          service:
            name: auth-microservice
            port: 
              number: 80
      - pathType: Prefix
        path: /usuario
        backend:
          service:
            name: usuarios-microservice
            port:
              number: 80
      - pathType: Prefix
        path: /proyecto
        backend:
          service:
            name: proyectos-microservice
            port:
              number: 80
      - pathType: Prefix
        path: /skills
        backend:
          service:
            name: tech-skills-microservice
            port:
              number: 80
      - pathType: Prefix
        path: /offers
        backend:
          service:
            name: offers-microservice
            port:
              number: 80
      - pathType: Prefix
        path: /pruebas
        backend:
          service:
            name: pruebas-microservice
            port:
              number: 80
      - pathType: Prefix
        path: /entrevistas
        backend:
          service:
            name: entrevistas-microservice
            port:
              number: 80
      - pathType: Prefix
        path: /grades
        backend:
          service:
            name: grades-microservice
            port:
              number: 80
