name: Unit tests

on:
  push:
    branches: 
      - main
      - develop
      - feature-**
jobs:
  users-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v1
      - name: Install environment
        working-directory: ./auth
        run: |
          pip install pipenv
          pipenv sync --system --dev
          export VIRTUAL_ENV="$(pipenv --venv)" PATH="$(pipenv --venv)/bin:$PATH"
      - name: Run unit tests
        working-directory: ./auth
        run: |
         coverage run -m unittest discover -s tests
          coverage report -m --fail-under=80

